@echo off
echo Starting Smiley Dental Clinic...
echo.
echo Disabling Turbopack...
echo TURBOPACK=0 > .env.local
echo.
echo Cleaning cache...
if exist .next rmdir /s /q .next
echo.
echo Starting server...
npm run dev
pause
